CREATE TABLE IF NOT EXISTS USUARIOS (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    ativo BOOLEAN DEFAULT true,
    senha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS RECEITAS (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    ingredientes TEXT NOT NULL,
    instrucoes TEXT NOT NULL,
    tempo_preparo_minutos INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES USUARIOS(id) ON DELETE CASCADE
);